travis:
  secure:
    BINSTAR_TOKEN: 3BPG+y8YuT2pfip2497azTLgOnqD5fwSAto2EGpWnDwWeoKKucHT4gozVIefwzPcUBRTFuTErPPNDnxkXExzLzMksrYIkIzDTBQJnbadxQH3ZTb38Jir87unxsV9y1Xlzxufk4Mk736vTFl3ylpxJXldD1IixZltEhTuzSNIUVQ/o3AV/eN2RRckyKjPzbG4wk661YWd8sDRgJMNLq6GqC3Ex7B0SVSbbtknIIhc+vBuDAJqv2WO4wb7Z9bqhCShRmMTq+vkEQTBDVjg+L2+F1eGItb+658cFCwRCGUgUgSTMepqUXNvEvJ/yw0gTwkfaHHED5NpjiCWHxCOiURiHbnU4AKHcdqdM6Motrf0undvM5Pj3ew9y33eS2CrAY5/OWCZyzmQZsciz5GJqwHub6PaNRR93Yr7n81z5ELqes/QiBedGTqHNFRAPBHPW7HGZq/pYBR+fb12lLLrHdvHHFsqHOtL/hw+NO4Q7EhGHzttxKolByaYRBVNNVV5/teUcCjhHHl6OzWd8ZwN0tI/5wROHoSgsgUxSLi26+fXV1bFet8x4lKbCDzpUniZ/lzJUznDT8WHxZzQ0X5WePeK50+R8wd0PsxdWBeLuuvsgaJQqUYTj6Gt/BmSNJo56rpijeTs05cTYlGALVLLkW8c8nvAyjtNZksbL4iep+G7VSo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
